### ISSUE TITLE
Organize backlog and sprint planning

### ISSUE THREAD

**Issue by Hana-ElGabry** [Hana-ElGabry/CareerPilot#3]
- [x] - Set up a GitHub backlog with all tasks.
- [x] - Define user stories for the project.
- [x] - Create a sprint plan for the next 2-3 weeks, outlining the tasks and timelines.
- [x] - Prepare for a sprint retrospective to reflect on what went well and what could be improved.
- [x] - Create a burndown chart in Excel to track sprint progress.
- [x] #25
- [x] - Ensure that branches or pull requests are created for each team member.
- [x] - Write descriptive comments when pushing to GitHub.
