### ISSUE TITLE
Design and develop project prototype

### ISSUE THREAD

**Issue by Hana-ElGabry** [Hana-ElGabry/CareerPilot#4]
- [ ] Create UI designs on Figma for the entire project.
- [x] Implement at least 3 main functions in the prototype:
- [x] Login and Registration
- [ ] Create and Print/Extract Profile (optional)
- [x] Search for Jobs with Filters
- [x] Search for Courses
- [x] Ensure the prototype is functional with these key features.
